### ISSUE TITLE
$domain Parameter

### ISSUE THREAD

**Issue by bkonia** [audunru/universal-analytics#1]
Hi Audun,

Very nice little library, much easier to work with than some of the ridiculously overcomplicated GAMP libraries I've come across. One suggestion though:

The GA JS library defaults to using the root domain when setting the cookie. However, your set() function doesn't set the domain parameter, so it binds the cookie to the hostname. Therefore, if you're using your library in conjunction with the JS library, you'll end up with two _ga cookies and users will be tracked independently by each library, which is not desirable.

I modified the set() function to include a $domain = null parameter, which gives the user the option to pass the cookie domain to the function. It would be nice if you updated it on your end, to include this enhancement.

**Comment by bkonia** [comment]
Actually, it would be better to add this parameter to the class construct function. That way, you only have to set it once:

```
    public function __construct ($cookieDomain = null) {
		$this->cookieDomain = $cookieDomain;
    }
```

`setcookie  ('_ga', '1.2.' . $cid, time ()+60*60*24*365*2, '/', $this->cookieDomain);`

**Comment by audunru** [comment]
Thanks! Sorry it took me ONE YEAR+.
